# Generated by Django 5.2.8 on 2025-11-30 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('categorias', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='publicado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
