# Generated by Django 5.2.8 on 2025-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_options_remove_articulo_publicado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseInspiradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
