# Generated by Django 5.2.8 on 2025-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('redes_sociales', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre nosotros', max_length=200)),
                ('descripcion', models.TextField()),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
